language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
api_key:
    secure: R/+byiFerJ4Wz9OrycAmzSLjnLuY1b08wyC5uS5oiuNcruPX3VjYtSJsq06hQ3BGAylVPyZ0BRrbSPKHR66TR4wJ2Zct2O/cak54kv1Bqp3WzKL4chL2W1nDguHx51qrtJtvZd6Nfki3sIeHCN3ZttgmEsmAgh+JjnImwQZg1QELpVDzr21benJx9ecdwfQjmvqEK5voKUJxsWNt3F0ZgWySlZDUHtYotW5nSTKBW0qsVxlt7OQl08t8m25ZZPykLJ1uFcTSEI5UBnXab4VJ3JPm+xSrSSVs/HrOrRgmOIc9WpIcIE6wj6wJKcgUzU/K3hQOmJiN3X3/8ufPIVLZecJpcdWenhULf+wJEnw3QUHToZO40GHNJarmL4PBnmnhWgBgBxlasmquXp6Z42+7t2j2yLr+OoBZZ92GBdMvvTH+0SRV7C1s3wL9htJcDwC2QaskkJEJt6fJFBmqI2XxxyWUizpIt4ZtMTATCRoRpZRIsNFEJZl0U4tjuuAJ5VmUI3iZDkGI7Krc8oGPeVPNRucX7OhX2ZwbjvqQcvpAe4TMZeAeTz9YoYfFaaFZlx9HK2RxOioLNtNrtcqxVF+0swQUPjJFAUP7yCmX+S8K9blciHu3nkJq9iLos/xkDmrqlLVOd/km4x38h7aRkSRHbgafUqbpU9eH8QmauN+AuVI=
app: merntemplate