language: node_js
node_js:
  - "stable"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
services:
  - mongodb
cache:
  directories:
  - node_modules
before_script:
  script: yarn seedTest
# deploy:
  # provider: heroku 
# api_key:
    # secure: Add heroku API key here
app: merntemplate